server {
    listen 8000;

    location /uploads {
        autoindex on;
        alias /var/www/media;
    }

    location / {
        proxy_pass              http://vulnerable_app:8000;
        proxy_set_header        Host $host;
        proxy_set_header        HTTP_AUTHORIZATION $http_authorization;
    }
}